In [1]:
# import config
import numpy as np
import os
import pandas as pd
import torch

In [2]:
from PIL import Image, ImageFile
from torch.utils.data import Dataset, DataLoader

In [5]:
anchors = [
    [(0.28, 0.22), (0.38, 0.48), (0.9, 0.78)],
    [(0.07, 0.15), (0.15, 0.11), (0.14, 0.29)],
    [(0.02, 0.03), (0.04, 0.07), (0.08, 0.06)],
]

In [34]:
S = [13, 26, 52]
scaled_anchors = torch.tensor(anchors) / (
        1 / torch.tensor(S).unsqueeze(1).unsqueeze(1).repeat(1, 3, 2)
)

In [35]:
scaled_anchors

tensor([[[ 3.6400,  2.8600],
         [ 4.9400,  6.2400],
         [11.7000, 10.1400]],

        [[ 1.8200,  3.9000],
         [ 3.9000,  2.8600],
         [ 3.6400,  7.5400]],

        [[ 1.0400,  1.5600],
         [ 2.0800,  3.6400],
         [ 4.1600,  3.1200]]])

In [33]:
torch.tensor(S).unsqueeze(1).unsqueeze(1).repeat(2,3,2)

tensor([[[13, 13],
         [13, 13],
         [13, 13]],

        [[26, 26],
         [26, 26],
         [26, 26]],

        [[52, 52],
         [52, 52],
         [52, 52]],

        [[13, 13],
         [13, 13],
         [13, 13]],

        [[26, 26],
         [26, 26],
         [26, 26]],

        [[52, 52],
         [52, 52],
         [52, 52]]])

In [22]:
torch.tensor(S).unsqueeze(1).shape

torch.Size([3, 1])

In [25]:
torch.tensor(S).unsqueeze(0)

tensor([[13, 26, 52]])

In [26]:
torch.tensor(S)

tensor([13, 26, 52])

In [32]:
torch.tensor(S).unsqueeze(1).unsqueeze(1)

tensor([[[13]],

        [[26]],

        [[52]]])

In [14]:
label_path = "/Users/skattish/Documents/img_process_learn/yolov3/PASCAL_VOC/labels/000001.txt"
bboxes = np.roll(np.loadtxt(fname=label_path, delimiter=" ", ndmin=2), 4, axis=1).tolist()

In [15]:
bboxes

[[0.34135977337110485, 0.609, 0.4164305949008499, 0.262, 11.0],
 [0.5070821529745043, 0.508, 0.9745042492917847, 0.972, 14.0]]

In [7]:
4%3

1